# 04. 최신 시장 검증 및 타 플랫폼 벤치마크

## 분석 목적

앞선 1·2차 EDA에서는 2021~2022년 Netflix Top 10 데이터를 기반으로
장기흥행 콘텐츠의 장르, 언어, 제작국가, 초기 성과 및 TMDB 메타데이터 특성을 분석했다.

이번 단계에서는 해당 결과가 최근 콘텐츠 시장에서도 어느 정도 유효한지 확인하기 위해
2026년 상반기 Netflix 공식 공개자료와 타 플랫폼의 게임 IP 기반 콘텐츠 사례를 비교한다.

단, 2026년 자료는 기존 Netflix Top 10 데이터와 수집 기준 및 지표가 다르므로
기존 long_hit 데이터와 직접 결합하지 않고 최신 시장 흐름을 확인하는 검증 자료로 활용한다.

In [2]:
# Excel(.xlsx) 파일을 읽기 위해 openpyxl 패키지를 설치

%pip install openpyxl


   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# 2026 최신 Netflix Global Weekly 데이터를 불러와 기본 구조와 기간을 확인

import pandas as pd

global_weekly_2026 = pd.read_excel(
    "../DATA/RAW/[엔터]Netflix_Top10_2026_H1/global_weekly_2026-09-03.xlsx"
)

print("데이터 크기:", global_weekly_2026.shape)
print("\n컬럼:")
print(global_weekly_2026.columns.tolist())

print("\n기간:")
print(global_weekly_2026["week"].min(), "~", global_weekly_2026["week"].max())

display(global_weekly_2026.head())

c:\Users\Main\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


데이터 크기: (10760, 9)

컬럼:
['week', 'category', 'weekly_rank', 'show_title', 'season_title', 'weekly_hours_viewed', 'runtime', 'weekly_views', 'cumulative_weeks_in_top_10']

기간:
2021-07-04 ~ 2026-08-23


,week,category,weekly_rank,show_title,season_title,weekly_hours_viewed,runtime,weekly_views,cumulative_weeks_in_top_10
0,2026-08-23,Films (English),1,Don't Say Good Luck,NaN,20300000,1.5833,12800000.0,2
1,2026-08-23,Films (English),2,The Last House,NaN,22400000,1.8667,12000000.0,3
2,2026-08-23,Films (English),3,Freefall: A Reckoning for Boeing,NaN,7500000,1.5833,4700000.0,1
3,2026-08-23,Films (English),4,72 HOURS,NaN,7000000,1.7500,4000000.0,5
4,2026-08-23,Films (English),5,The Dating App Killer: The Monica White Story,NaN,4900000,1.4500,3400000.0,1


In [4]:
# Global Weekly 전체 데이터에서 2026년 상반기 데이터만 추출

global_weekly_2026["week"] = pd.to_datetime(
    global_weekly_2026["week"]
)

global_h1_2026 = global_weekly_2026[
    (global_weekly_2026["week"] >= "2026-01-01")
    & (global_weekly_2026["week"] <= "2026-06-30")
].copy()

print("2026 H1 데이터 크기:", global_h1_2026.shape)

print(
    "2026 H1 기간:",
    global_h1_2026["week"].min(),
    "~",
    global_h1_2026["week"].max()
)

print("\n카테고리:")
print(global_h1_2026["category"].value_counts())

display(global_h1_2026.head())

2026 H1 데이터 크기: (1040, 9)
2026 H1 기간: 2026-01-04 00:00:00 ~ 2026-06-28 00:00:00

카테고리:
category
Films (English)        260
Films (Non-English)    260
TV (English)           260
TV (Non-English)       260
Name: count, dtype: int64


,week,category,weekly_rank,show_title,season_title,weekly_hours_viewed,runtime,weekly_views,cumulative_weeks_in_top_10
320,2026-06-28,Films (English),1,Voicemails for Isabelle,NaN,60900000,1.9667,31000000.0,2
321,2026-06-28,Films (English),2,Little Brother,NaN,23400000,1.6667,14000000.0,1
322,2026-06-28,Films (English),3,Maternal Instinct,NaN,13700000,1.6167,8500000.0,3
323,2026-06-28,Films (English),4,Swapped,NaN,7800000,1.7000,4600000.0,9
324,2026-06-28,Films (English),5,Office Romance,NaN,8200000,1.9167,4300000.0,4


In [5]:
# 2026년 상반기 Global Weekly 데이터에서 TV 콘텐츠만 추출

tv_h1_2026 = global_h1_2026[
    global_h1_2026["category"].str.contains("TV")
].copy()

print("2026 H1 TV 데이터 크기:", tv_h1_2026.shape)

print("\n카테고리:")
print(tv_h1_2026["category"].value_counts())

print("\n작품 수:")
print(tv_h1_2026["show_title"].nunique())

display(tv_h1_2026.head())

2026 H1 TV 데이터 크기: (520, 9)

카테고리:
category
TV (English)        260
TV (Non-English)    260
Name: count, dtype: int64

작품 수:
186


,week,category,weekly_rank,show_title,season_title,weekly_hours_viewed,runtime,weekly_views,cumulative_weeks_in_top_10
340,2026-06-28,TV (English),1,I Will Find You,I Will Find You: Limited Series,187200000,5.4833,34100000.0,2
341,2026-06-28,TV (English),2,Avatar: The Last Airbender,Avatar: The Last Airbender: Season 2,64600000,7.4667,8700000.0,1
342,2026-06-28,TV (English),3,Avatar: The Last Airbender,Avatar: The Last Airbender: Season 1,21700000,7.2500,3000000.0,7
343,2026-06-28,TV (English),4,Raw,"Raw: June 22, 2026",4300000,1.7833,2300000.0,1
344,2026-06-28,TV (English),5,AMERICA'S SWEETHEARTS: Dallas Cowboys Cheerlea...,AMERICA'S SWEETHEARTS: Dallas Cowboys Cheerlea...,15300000,7.0167,2200000.0,2


In [6]:
# 2026년 상반기 TV 콘텐츠별 Top 10 최대 유지 주차를 확인

tv_2026_duration = (
    tv_h1_2026.groupby(
        ["show_title", "category"]
    )["cumulative_weeks_in_top_10"]
    .max()
    .reset_index()
    .rename(
        columns={
            "cumulative_weeks_in_top_10": "max_cumulative_weeks"
        }
    )
    .sort_values(
        "max_cumulative_weeks",
        ascending=False
    )
)

print("TV 콘텐츠 수:", len(tv_2026_duration))

display(tv_2026_duration.head(20))

TV 콘텐츠 수: 186


,show_title,category,max_cumulative_weeks
138,Stranger Things,TV (English),29
26,Bridgerton,TV (English),20
164,The Night Agent,TV (English),17
103,ONE PIECE,TV (English),11
39,Dynamite Kiss,TV (Non-English),9
19,Berlin and the Jewels of Paris,TV (Non-English),8
72,Juvenile Justice,TV (Non-English),8
23,Bloodhounds,TV (Non-English),8
99,My Royal Nemesis,TV (Non-English),8
12,Avatar: The Last Airbender,TV (English),7


In [7]:
# 2026년 상반기 동안 각 TV 콘텐츠가 실제로 Top 10에 등장한 주 수를 계산

tv_2026_observed_weeks = (
    tv_h1_2026.groupby(
        ["show_title", "category"]
    )["week"]
    .nunique()
    .reset_index()
    .rename(
        columns={
            "week": "observed_weeks_2026_h1"
        }
    )
    .sort_values(
        "observed_weeks_2026_h1",
        ascending=False
    )
)

display(tv_2026_observed_weeks.head(20))

,show_title,category,observed_weeks_2026_h1
112,Raw,TV (English),23
26,Bridgerton,TV (English),9
99,My Royal Nemesis,TV (Non-English),8
132,Sold Out on You,TV (Non-English),7
55,HIS & HERS,TV (English),7
7,Alpha Males,TV (Non-English),7
122,Salish & Jordan Matter,TV (English),6
34,Danny Go!,TV (English),6
180,Unfamiliar,TV (Non-English),6
20,Berlin and the Lady with an Ermine,TV (Non-English),5


In [8]:
# 2026년 상반기 TV 콘텐츠의 실제 Top 10 등장 주 수 분포를 확인

print(
    tv_2026_observed_weeks["observed_weeks_2026_h1"].describe()
)

display(
    tv_2026_observed_weeks.head(20)
)

count    186.000000
mean       2.612903
std        2.166239
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       23.000000
Name: observed_weeks_2026_h1, dtype: float64


,show_title,category,observed_weeks_2026_h1
112,Raw,TV (English),23
26,Bridgerton,TV (English),9
99,My Royal Nemesis,TV (Non-English),8
132,Sold Out on You,TV (Non-English),7
55,HIS & HERS,TV (English),7
7,Alpha Males,TV (Non-English),7
122,Salish & Jordan Matter,TV (English),6
34,Danny Go!,TV (English),6
180,Unfamiliar,TV (Non-English),6
20,Berlin and the Lady with an Ermine,TV (Non-English),5


In [9]:
# 기존 2021~22 분석과 동일하게 TV 콘텐츠를 시즌·파트 단위 content_key로 구분

tv_h1_2026["content_key"] = tv_h1_2026["season_title"].fillna(
    tv_h1_2026["show_title"]
)

print("show_title 기준 작품 수:", tv_h1_2026["show_title"].nunique())
print("content_key 기준 콘텐츠 수:", tv_h1_2026["content_key"].nunique())

display(
    tv_h1_2026[
        ["show_title", "season_title", "content_key"]
    ].drop_duplicates().head(20)
)

show_title 기준 작품 수: 186
content_key 기준 콘텐츠 수: 224


,show_title,season_title,content_key
340,I Will Find You,I Will Find You: Limited Series,I Will Find You: Limited Series
341,Avatar: The Last Airbender,Avatar: The Last Airbender: Season 2,Avatar: The Last Airbender: Season 2
342,Avatar: The Last Airbender,Avatar: The Last Airbender: Season 1,Avatar: The Last Airbender: Season 1
343,Raw,"Raw: June 22, 2026","Raw: June 22, 2026"
344,AMERICA'S SWEETHEARTS: Dallas Cowboys Cheerlea...,AMERICA'S SWEETHEARTS: Dallas Cowboys Cheerlea...,AMERICA'S SWEETHEARTS: Dallas Cowboys Cheerlea...
345,Salish & Jordan Matter,Salish & Jordan Matter: Season 1,Salish & Jordan Matter: Season 1
346,Sweet Magnolias,Sweet Magnolias: Season 5,Sweet Magnolias: Season 5
347,Salish & Jordan Matter,Salish & Jordan Matter: Season 2,Salish & Jordan Matter: Season 2
348,The Amazing Digital Circus,The Amazing Digital Circus: Season 1,The Amazing Digital Circus: Season 1
349,The Last Ship,The Last Ship: Season 1,The Last Ship: Season 1


In [10]:
# 2026년 상반기 TV 콘텐츠의 시즌·파트별 실제 Top 10 등장 주 수를 계산

tv_2026_observed_weeks = (
    tv_h1_2026.groupby(
        ["content_key", "show_title", "category"]
    )["week"]
    .nunique()
    .reset_index()
    .rename(columns={
        "week": "observed_weeks_2026_h1"
    })
    .sort_values(
        "observed_weeks_2026_h1",
        ascending=False
    )
)

print(
    tv_2026_observed_weeks[
        "observed_weeks_2026_h1"
    ].describe()
)

display(tv_2026_observed_weeks.head(20))

count    224.000000
mean       2.321429
std        1.492668
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        9.000000
Name: observed_weeks_2026_h1, dtype: float64


,content_key,show_title,category,observed_weeks_2026_h1
31,Bridgerton: Season 4,Bridgerton,TV (English),9
104,My Royal Nemesis: Limited Series,My Royal Nemesis,TV (Non-English),8
162,Sold Out on You: Limited Series,Sold Out on You,TV (Non-English),7
60,HIS & HERS: Limited Series,HIS & HERS,TV (English),7
151,Salish & Jordan Matter: Season 1,Salish & Jordan Matter,TV (English),6
218,Unfamiliar: Season 1,Unfamiliar,TV (Non-English),6
39,Danny Go!: Season 1,Danny Go!,TV (English),6
22,Berlin and the Lady with an Ermine: Limited Se...,Berlin and the Lady with an Ermine,TV (Non-English),5
95,Man on Fire: Season 1,Man on Fire,TV (English),5
105,Nemesis: Season 1,Nemesis,TV (English),5


In [11]:
# 2026 H1 시즌·파트 단위에서 5주 이상 Top 10에 등장한 콘텐츠를 장기 유지 후보로 확인

tv_2026_observed_weeks["long_stay_2026"] = (
    tv_2026_observed_weeks["observed_weeks_2026_h1"] >= 5
).astype(int)

print(tv_2026_observed_weeks["long_stay_2026"].value_counts())
print(
    "장기 유지 비율:",
    round(tv_2026_observed_weeks["long_stay_2026"].mean() * 100, 2),
    "%"
)

display(
    tv_2026_observed_weeks[
        tv_2026_observed_weeks["long_stay_2026"] == 1
    ]
)

long_stay_2026
0    204
1     20
Name: count, dtype: int64
장기 유지 비율: 8.93 %


,content_key,show_title,category,observed_weeks_2026_h1,long_stay_2026
31,Bridgerton: Season 4,Bridgerton,TV (English),9,1
104,My Royal Nemesis: Limited Series,My Royal Nemesis,TV (Non-English),8,1
162,Sold Out on You: Limited Series,Sold Out on You,TV (Non-English),7,1
60,HIS & HERS: Limited Series,HIS & HERS,TV (English),7,1
151,Salish & Jordan Matter: Season 1,Salish & Jordan Matter,TV (English),6,1
218,Unfamiliar: Season 1,Unfamiliar,TV (Non-English),6,1
39,Danny Go!: Season 1,Danny Go!,TV (English),6,1
22,Berlin and the Lady with an Ermine: Limited Se...,Berlin and the Lady with an Ermine,TV (Non-English),5,1
95,Man on Fire: Season 1,Man on Fire,TV (English),5,1
105,Nemesis: Season 1,Nemesis,TV (English),5,1


In [12]:
# 2026 H1 장기 유지 여부별 English / Non-English 비중을 비교

language_group_2026 = (
    tv_2026_observed_weeks.groupby(
        ["category", "long_stay_2026"]
    )
    .size()
    .reset_index(name="content_count")
)

language_group_2026

,category,long_stay_2026,content_count
0,TV (English),0,116
1,TV (English),1,8
2,TV (Non-English),0,88
3,TV (Non-English),1,12


In [13]:
# 2026 H1 English / Non-English TV 콘텐츠의 장기 유지 비율을 계산

category_long_stay_summary = (
    tv_2026_observed_weeks
    .groupby("category")["long_stay_2026"]
    .agg(["count", "sum", "mean"])
    .reset_index()
)

category_long_stay_summary["long_stay_rate"] = (
    category_long_stay_summary["mean"] * 100
)

category_long_stay_summary = category_long_stay_summary[
    ["category", "count", "sum", "long_stay_rate"]
]

category_long_stay_summary

,category,count,sum,long_stay_rate
0,TV (English),124,8,6.451613
1,TV (Non-English),100,12,12.000000


In [15]:
# 2021~2022 Netflix TV 분석 데이터를 불러와 최신 데이터와 비교할 준비

netflix_tv_df = pd.read_csv(
    "../DATA/PROCESSED/netflix_tv_analysis.csv"
)

print("2021~2022 TV 데이터 크기:", netflix_tv_df.shape)
print(netflix_tv_df.columns.tolist())

display(netflix_tv_df.head())

2021~2022 TV 데이터 크기: (159, 13)
['content_key', 'show_title', 'category', 'first_week', 'last_week', 'first_cumulative', 'max_cumulative', 'right_censored', 'long_hit', 'first_rank', 'first_week_hours', 'log_first_week_hours', 'initial_country_reach']


,content_key,show_title,category,first_week,last_week,first_cumulative,max_cumulative,right_censored,long_hit,first_rank,first_week_hours,log_first_week_hours,initial_country_reach
0,A Tale Dark & Grimm: Season 1,A Tale Dark & Grimm,TV (English),2021-10-17,2021-10-17,1,1,False,0,7,18730000,16.745637,19.0
1,AlRawabi School for Girls: Limited Series,AlRawabi School for Girls,TV (Non-English),2021-08-15,2021-08-29,1,3,False,0,6,11620000,16.268238,27.0
2,Alice in Borderland: Season 1,Alice in Borderland,TV (Non-English),2021-09-26,2021-10-24,1,5,False,1,8,10890000,16.203356,13.0
3,All American: Season 3,All American,TV (English),2021-08-01,2021-08-29,1,5,False,1,2,43970000,17.599018,1.0
4,Another Life: Season 2,Another Life,TV (English),2021-10-24,2021-10-24,1,1,False,0,9,15760000,16.572986,4.0


In [16]:
# 2021~2022 TV 데이터의 English / Non-English 장기흥행 비율을 계산

category_long_hit_2021 = (
    netflix_tv_df
    .groupby("category")["long_hit"]
    .agg(["count", "sum", "mean"])
    .reset_index()
)

category_long_hit_2021["long_hit_rate"] = (
    category_long_hit_2021["mean"] * 100
)

category_long_hit_2021 = category_long_hit_2021[
    ["category", "count", "sum", "long_hit_rate"]
]

category_long_hit_2021

,category,count,sum,long_hit_rate
0,TV (English),91,24,26.373626
1,TV (Non-English),68,20,29.411765


In [17]:
# 2021~2022와 2026 H1의 English / Non-English 장기 유지 경향을 한 표로 비교

comparison_category = pd.DataFrame({
    "category": ["TV (English)", "TV (Non-English)"],
    "2021_22_rate": [26.37, 29.41],
    "2026_h1_rate": [6.45, 12.00]
})

comparison_category

,category,2021_22_rate,2026_h1_rate
0,TV (English),26.37,6.45
1,TV (Non-English),29.41,12.00


### English / Non-English 장기 유지 경향 비교

2021~2022년 분석에서는 TV (English)의 장기흥행 비율이 26.37%,
TV (Non-English)는 29.41%로 비영어권 콘텐츠가 조금 더 높게 나타났다.

2026년 상반기에는 5주 이상 Global Top 10에 등장한 콘텐츠를 장기 유지 후보로 정의했으며,
TV (English)는 6.45%, TV (Non-English)는 12.00%로 나타났다.

두 시기의 장기 유지 기준이 동일하지 않기 때문에 비율의 절대값을 직접 비교할 수는 없지만,
두 시기 모두 비영어권 TV 콘텐츠에서 상대적으로 높은 장기 유지 경향이 확인되었다.

따라서 두 시기의 장기 유지 기준은 다르지만,
비영어권 TV 콘텐츠가 영어권보다 상대적으로 높은 장기 유지 비율을 보였다는 점에서
유사한 방향성이 관찰되었다.